# Generated by Django 5.2.4 on 2025-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='images',
            field=models.ImageField(default='meal_images/default_meal.jpg', upload_to='meal_images'),
        ),
    ]
