# Generated by Django 5.2.4 on 2025-08-17 15:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_meal_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(db_default=0, verbose_name='stock count'),
        ),
        migrations.CreateModel(
            name='OrderTransction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='amount paid($)')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='pending', max_length=9, verbose_name='delivery status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal')),
            ],
        ),
    ]
